---
title: "Almond Yield Profit Model"
subtitle: "EDS 230 - Assignment #3"
date: "04/21/2025"
format: html
author: "Jordan Sibley and Marina Kochuten" 
editor_options: 
  chunk_output_type: console
---

## Overview



## Setup

```{r}
# Load libraries
library(tidyverse)
library(here)
library(purrr)
```

## Data Prep

```{r}
# Read in climate data
data <- read.table("data/clim.txt", header = TRUE, sep = " ", stringsAsFactors = FALSE)

# Filter not complete years - no Jan or Feb data for 1988
data_clean <- data |> 
  filter(year != 1988)
```

## Running the Model

```{r}
# Source function
source(here("R", "almond-yield-profit.R"))

# Calculate annual almond profits
almond_profits <- calculate_yield_and_profit(data_clean)
```

## Informal Sensitivity Analysis

```{r}
# Generate sample data
almond_price = rnorm(mean = 2000, sd = 200, n = 200)
cost_per_acre = rnorm(mean = 1000, sd = 50, n = 200)

# Bind together
parms <- cbind.data.frame(almond_price, cost_per_acre)

# Pmap for sensitivity analysis
results <- parms %>% pmap(calculate_yield_and_profit, data_clean
)

# Check
results[[1]]
length(results)

# Extract results
mean_profit <- map_df(results, `[`, c("profit", "year", "almond_yield"))

# Add parameter values
mean_profit <- cbind.data.frame(mean_profit, parms)

# Force ggplot to not display numbers in scientific notation
options(scipen = 999)


# Plot annual profit uncertainty
ggplot(mean_profit, 
       aes(as.factor(year), profit, group = year)) +
  geom_boxplot() +
  labs(x = "Year",
       y = "Mean Annual Profit (USD)",
       title = "Annual Almond Profit Uncertainty") +
  scale_y_continuous(labels = scales::label_comma()) +
  theme_minimal()

# Plot overall profit uncertainty
ggplot(mean_profit, 
       aes(y = profit)) +
  geom_boxplot() +
  labs(y = "Mean Annual Profit (USD)",
       title = "Overall Almond Profit Uncertainty") +
  scale_y_continuous(labels = scales::label_comma()) +
  theme_minimal() +
  theme(
    axis.text.x = element_blank()
  )
```


## Summary and Interpretation of Results







